# Generated by Django 5.2 on 2025-04-06 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_progressentry_height_progressentry_muscle_mass_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressentry',
            old_name='body_fat_percentage',
            new_name='body_fat',
        ),
        migrations.RemoveField(
            model_name='progressentry',
            name='height',
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
