# Generated by Django 5.2 on 2025-04-11 00:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_rename_body_fat_percentage_progressentry_body_fat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressentry',
            options={'ordering': ['-date'], 'verbose_name': 'Progresso', 'verbose_name_plural': 'Progresso'},
        ),
        migrations.AlterUniqueTogether(
            name='progressentry',
            unique_together={('user', 'date')},
        ),
    ]
