# Generated by Django 5.1 on 2025-07-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_alter_progressentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressentry',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
