# Generated by Django 5.1 on 2025-07-28 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_progressentry_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressentry',
            name='arm_circumference',
            field=models.FloatField(blank=True, help_text='Circunferência do braço em cm.', null=True),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='calf_circumference',
            field=models.FloatField(blank=True, help_text='Circunferência da panturrilha em cm.', null=True),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='chest_circumference',
            field=models.FloatField(blank=True, help_text='Circunferência do peito em cm.', null=True),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 28, 14, 16, 13, 328234, tzinfo=datetime.timezone.utc), help_text='Data e hora de criação do registro.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progressentry',
            name='hip_circumference',
            field=models.FloatField(blank=True, help_text='Circunferência do quadril em cm.', null=True),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='photo_url_after',
            field=models.URLField(blank=True, help_text="URL da foto 'depois'.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='photo_url_before',
            field=models.URLField(blank=True, help_text="URL da foto 'antes'.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='thigh_circumference',
            field=models.FloatField(blank=True, help_text='Circunferência da coxa em cm.', null=True),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro.'),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='waist_circumference',
            field=models.FloatField(blank=True, help_text='Circunferência da cintura em cm.', null=True),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='body_fat',
            field=models.FloatField(blank=True, help_text='Percentual de gordura corporal (%).', null=True),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='date',
            field=models.DateField(help_text='Data do registro de progresso.'),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='muscle_mass',
            field=models.FloatField(blank=True, help_text='Massa muscular em quilogramas (kg).', null=True),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionais sobre o progresso.', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='weight',
            field=models.FloatField(help_text='Peso em quilogramas (kg).'),
        ),
    ]
