# Generated by Django 5.2 on 2025-04-07 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatmessage_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='response',
            new_name='bot_response',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='user_message',
        ),
    ]
