# Generated by Django 5.2 on 2025-04-11 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_rename_response_chatmessage_bot_response_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Mensagem de Chat', 'verbose_name_plural': 'Mensagens de Chat'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='bot_response',
            field=models.TextField(verbose_name='Resposta da IA'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user_message',
            field=models.TextField(verbose_name='Mensagem do Usuário'),
        ),
    ]
