# Generated by Django 5.1 on 2025-04-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('perda_peso', 'Perda de Peso'), ('ganho_muscular', 'Ganho Muscular'), ('flexibilidade', 'Flexibilidade')], max_length=50, null=True),
        ),
    ]
