# Generated by Django 5.1 on 2025-07-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_fitness_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentário'), ('lightly_active', 'Levemente ativo'), ('moderately_active', 'Moderadamente ativo'), ('very_active', 'Muito ativo'), ('extremely_active', 'Extremamente ativo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('perda_peso', 'Perda de peso'), ('ganho_muscular', 'Ganho de massa muscular'), ('manutencao', 'Manutenção'), ('resistencia', 'Resistência')], max_length=50, null=True),
        ),
    ]
