# Generated by Django 5.1 on 2025-07-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_activity_level_alter_user_fitness_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Feminino'), ('other', 'Outro')], help_text='Gênero do usuário.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentário'), ('lightly_active', 'Levemente ativo'), ('moderately_active', 'Moderadamente ativo'), ('very_active', 'Muito ativo'), ('extremely_active', 'Extremamente ativo')], help_text='Nível de atividade física do usuário.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Data de nascimento do usuário.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dietary_restrictions',
            field=models.TextField(blank=True, help_text="Restrições dietéticas do usuário (ex: 'vegetariano', 'sem glúten').", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Endereço de e-mail único do usuário.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Primeiro nome do usuário.', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('perda_peso', 'Perda de peso'), ('ganho_muscular', 'Ganho de massa muscular'), ('manutencao', 'Manutenção'), ('resistencia', 'Resistência')], help_text='Objetivo de fitness do usuário.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, help_text='Altura atual do usuário em cm.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='Sobrenome do usuário.', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, help_text='Peso atual do usuário em kg.', null=True),
        ),
    ]
