# Generated by Django 5.2 on 2025-04-08 19:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_rename_completed_at_workoutlog_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutfeedback',
            name='feedback_text',
        ),
        migrations.RemoveField(
            model_name='workoutfeedback',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='user',
        ),
        migrations.AddField(
            model_name='workoutfeedback',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutfeedback',
            name='workout_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.workoutlog'),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='duracao',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='nota',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('moderada', 'Moderada'), ('alta', 'Alta')], default='moderada', max_length=10),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('musculacao', 'Musculação'), ('flexibilidade', 'Flexibilidade')], default='musculacao', max_length=30),
        ),
    ]
