# Generated by Django 5.1 on 2025-04-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_workoutlog_duracao_alter_workoutlog_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='focus',
            field=models.CharField(choices=[('fullbody', 'Full Body'), ('superior', 'Membros Superiores'), ('inferior', 'Membros Inferiores')], default='fullbody', max_length=20),
        ),
    ]
