# Generated by Django 5.1 on 2025-07-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workout_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(default='iniciante', max_length=20),
        ),
        migrations.AddField(
            model_name='workout',
            name='equipment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workout',
            name='muscle_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workout',
            name='focus',
            field=models.CharField(choices=[('fullbody', 'Full Body'), ('superior', 'Membros Superiores'), ('inferior', 'Membros Inferiores'), ('core', 'Core')], default='fullbody', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('musculacao', 'Musculação'), ('flexibilidade', 'Flexibilidade'), ('yoga', 'Yoga')], default='musculacao', max_length=30),
        ),
    ]
