# Generated by Django 5.1 on 2025-07-26 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_workout_description_workout_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='completed_date',
            field=models.DateField(blank=True, help_text='Data em que o treino foi concluído pela última vez.', null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, help_text='Nome gerado para o treino.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='rating',
            field=models.FloatField(blank=True, help_text='Avaliação média do treino (1-5 estrelas).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('skipped', 'Pulado')], default='pending', help_text='Status atual do treino (pendente, concluído, etc.).', max_length=50),
        ),
        migrations.AddField(
            model_name='workout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workoutfeedback',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='workouts.workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='carga',
            field=models.PositiveIntegerField(default=0, help_text='Carga padrão em kg (se aplicável).'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição detalhada do treino.', null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(choices=[('iniciante', 'Iniciante'), ('moderado', 'Moderado'), ('avancado', 'Avançado')], default='iniciante', help_text='Nível de dificuldade do treino.', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.DurationField(help_text='Duração do treino (timedelta).'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='equipment',
            field=models.JSONField(blank=True, default=list, help_text='Equipamentos necessários em formato JSON (lista de strings).'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.TextField(blank=True, help_text='Detalhes dos exercícios em formato JSON string.'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='focus',
            field=models.CharField(choices=[('fullbody', 'Full Body'), ('superior', 'Membros Superiores'), ('inferior', 'Membros Inferiores'), ('core', 'Core')], default='fullbody', help_text='Foco principal do treino.', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='frequency',
            field=models.CharField(blank=True, help_text="Frequência recomendada (ex: '3x por semana').", max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='muscle_groups',
            field=models.JSONField(blank=True, default=list, help_text='Grupos musculares alvo em formato JSON (lista de strings).'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='series_reps',
            field=models.CharField(blank=True, help_text="Séries e repetições padrão (ex: '3x12').", max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='comments',
            field=models.TextField(blank=True, help_text='Comentários adicionais do usuário.', null=True),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='rating',
            field=models.IntegerField(help_text='Avaliação (1-5 estrelas).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='workout_log',
            field=models.ForeignKey(blank=True, help_text='Log de treino associado (opcional).', null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.workoutlog'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='duracao',
            field=models.IntegerField(help_text='Duração real do treino em minutos.'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='nota',
            field=models.IntegerField(help_text='Nota/avaliação do treino realizado (1-5).'),
        ),
    ]
