# Generated by Django 5.1 on 2025-07-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_workout_completed_date_workout_name_workout_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', help_text='Nível de dificuldade do treino.', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('skipped', 'Pulado'), ('recommended', 'Recomendado'), ('archived', 'Arquivado')], default='pending', help_text='Status atual do treino (pendente, concluído, etc.).', max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('musculacao', 'Musculação'), ('flexibilidade', 'Flexibilidade'), ('yoga', 'Yoga'), ('strength', 'Strength'), ('hiit', 'HIIT')], default='musculacao', max_length=30),
        ),
    ]
