# Generated by Django 5.1 on 2025-07-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_workout_difficulty_alter_workout_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='focus',
            field=models.CharField(choices=[('fullbody', 'Full Body'), ('superior', 'Membros Superiores'), ('inferior', 'Membros Inferiores'), ('core', 'Core')], default='fullbody', help_text='Foco principal do treino.', max_length=255),
        ),
    ]
