# Generated by Django 5.1 on 2025-07-30 18:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_alter_workout_focus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-created_at'], 'verbose_name': 'Treino', 'verbose_name_plural': 'Treinos'},
        ),
        migrations.AlterModelOptions(
            name='workoutfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback de Treino', 'verbose_name_plural': 'Feedbacks de Treino'},
        ),
        migrations.AlterModelOptions(
            name='workoutlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log de Treino', 'verbose_name_plural': 'Logs de Treino'},
        ),
        migrations.AlterField(
            model_name='workout',
            name='carga',
            field=models.PositiveIntegerField(default=0, help_text='Carga padrão em kg (se aplicável, pode ser 0 para peso corporal).'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do treino.'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.DurationField(help_text='Duração planejada do treino (timedelta).'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='equipment',
            field=models.JSONField(blank=True, default=list, help_text="Lista de equipamentos necessários (e.g., ['Halteres', 'Barra'])."),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.TextField(blank=True, help_text='Detalhes dos exercícios em formato JSON string (lista de objetos).'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='focus',
            field=models.CharField(choices=[('fullbody', 'Corpo Inteiro'), ('upper_body', 'Membros Superiores'), ('lower_body', 'Membros Inferiores'), ('core', 'Core'), ('cardio', 'Cardio'), ('flexibility', 'Flexibilidade'), ('custom', 'Personalizado')], default='fullbody', help_text='Foco principal do treino (e.g., Membros Superiores, Corpo Inteiro).', max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='frequency',
            field=models.CharField(blank=True, help_text="Frequência recomendada para o treino (ex: '3x por semana').", max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('moderada', 'Moderada'), ('alta', 'Alta')], default='moderada', help_text='Nível de intensidade do treino.', max_length=10),
        ),
        migrations.AlterField(
            model_name='workout',
            name='muscle_groups',
            field=models.JSONField(blank=True, default=list, help_text="Lista de grupos musculares alvo específicos (e.g., ['Tríceps', 'Bíceps'])."),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, help_text='Nome gerado ou customizado para o treino.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='series_reps',
            field=models.CharField(blank=True, help_text="Séries e repetições padrão para o treino (ex: '3x12').", max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do treino.'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(help_text='Usuário ao qual o treino pertence.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('musculacao', 'Musculação'), ('flexibilidade', 'Flexibilidade'), ('yoga', 'Yoga'), ('strength', 'Força'), ('hiit', 'HIIT')], default='musculacao', help_text='Tipo geral do treino (e.g., Musculação, Cardio).', max_length=30),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='comments',
            field=models.TextField(blank=True, help_text='Comentários adicionais do usuário sobre o treino.', null=True),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora do feedback.'),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='rating',
            field=models.IntegerField(help_text='Avaliação do treino (1-5 estrelas).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='user',
            field=models.ForeignKey(help_text='Usuário que forneceu o feedback.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='workout',
            field=models.ForeignKey(blank=True, help_text='Treino avaliado.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='workouts.workout'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora do registro do log.'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='workout',
            field=models.ForeignKey(help_text='Treino ao qual este log se refere.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workouts.workout'),
        ),
    ]
