# Generated by Django 5.1 on 2025-07-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_alter_workout_options_alter_workoutfeedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='carga_utilizada',
            field=models.CharField(blank=True, help_text="Carga geral utilizada no treino (ex: '50kg', 'peso corporal').", max_length=100, null=True),
        ),
    ]
