# Generated by Django 5.1 on 2025-07-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_workoutlog_carga_utilizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='carga_utilizada',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='exercise_logs',
            field=models.JSONField(blank=True, default=list, help_text='Detalhes de séries, repetições e carga por exercício.'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('skipped', 'Pulado'), ('recommended', 'Recomendado'), ('archived', 'Arquivado'), ('in_progress', 'Em Progresso')], default='pending', help_text='Status atual do treino (pendente, concluído, etc.).', max_length=50),
        ),
    ]
