# Generated by Django 5.2 on 2025-04-04 20:30

import diets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('breakfast', 'Café da manhã'), ('lunch', 'Almoço'), ('dinner', 'Jantar'), ('snack', 'Lanche'), ('afternoon_snack', 'Lanche da Tarde')], max_length=20)),
                ('calories', models.FloatField(validators=[diets.models.validate_positive])),
                ('protein', models.FloatField(validators=[diets.models.validate_positive])),
                ('carbs', models.FloatField(validators=[diets.models.validate_positive])),
                ('fat', models.FloatField(validators=[diets.models.validate_positive])),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Dietas',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(max_length=50)),
                ('intensity', models.CharField(max_length=20)),
                ('duration', models.DurationField()),
                ('exercises', models.TextField()),
                ('series_reps', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diets_workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
            },
        ),
    ]
