# Generated by Django 5.2 on 2025-04-08 16:28

import diets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_dietfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='carga',
            field=models.FloatField(default=0, validators=[diets.models.validate_positive]),
        ),
    ]
