# Generated by Django 5.2 on 2025-04-08 17:59

import diets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_diet_carga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='carga',
        ),
        migrations.AddField(
            model_name='workout',
            name='carga',
            field=models.FloatField(default=0, validators=[diets.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
