# Generated by Django 5.2 on 2025-04-11 00:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0004_remove_diet_carga_workout_carga_alter_workout_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diet',
            options={'ordering': ['-date'], 'verbose_name': 'Dieta', 'verbose_name_plural': 'Dietas'},
        ),
        migrations.AlterModelOptions(
            name='dietfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback de Dieta', 'verbose_name_plural': 'Feedbacks de Dieta'},
        ),
        migrations.AlterField(
            model_name='dietfeedback',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='diets.diet'),
        ),
        migrations.AlterField(
            model_name='dietfeedback',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
