# Generated by Django 5.1 on 2025-07-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0006_alter_diet_options_diet_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='goal',
            field=models.CharField(blank=True, choices=[('perda_peso', 'Perda de peso'), ('ganho_muscular', 'Ganho de massa muscular'), ('manutencao', 'Manutenção')], help_text='Objetivo fitness principal para o plano de dieta.', max_length=50, null=True),
        ),
    ]
