# Generated by Django 5.1 on 2025-07-29 20:49

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0008_alter_diet_calories_alter_diet_carbs_alter_diet_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumedmeallog',
            name='carbs_consumed',
            field=models.FloatField(blank=True, help_text='Carboidratos consumidos (g).', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='consumedmeallog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data da refeição consumida.'),
        ),
        migrations.AlterField(
            model_name='consumedmeallog',
            name='fat_consumed',
            field=models.FloatField(blank=True, help_text='Gordura consumida (g).', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='consumedmeallog',
            name='food_items',
            field=models.TextField(help_text='Descrição dos alimentos consumidos.'),
        ),
        migrations.AlterField(
            model_name='consumedmeallog',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionais sobre a refeição.', null=True),
        ),
        migrations.AlterField(
            model_name='consumedmeallog',
            name='protein_consumed',
            field=models.FloatField(blank=True, help_text='Proteína consumida (g).', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='consumedmeallog',
            name='time',
            field=models.TimeField(blank=True, help_text='Hora da refeição consumida.', null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Data da criação/sugestão da refeição.'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='dietary_restrictions',
            field=models.JSONField(blank=True, default=list, help_text='Restrições alimentares em JSON.'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='goal',
            field=models.CharField(blank=True, choices=[('perda_peso', 'Perda de peso'), ('ganho_muscular', 'Ganho de massa muscular'), ('manutencao', 'Manutenção'), ('resistencia', 'Resistência')], help_text='Objetivo do plano.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='ingredients',
            field=models.JSONField(blank=True, default=list, help_text='Lista de ingredientes em JSON.'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='meal',
            field=models.CharField(choices=[('breakfast', 'Café da manhã'), ('lunch', 'Almoço'), ('dinner', 'Jantar'), ('snack', 'Lanche'), ('afternoon_snack', 'Lanche da Tarde'), ('pre_workout', 'Pré-treino'), ('post_workout', 'Pós-treino')], help_text='Tipo de refeição.', max_length=20),
        ),
        migrations.AlterField(
            model_name='diet',
            name='name',
            field=models.CharField(blank=True, help_text='Nome da refeição.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='preferred_cuisine',
            field=models.CharField(blank=True, help_text='Culinária preferida.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='preparation_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo de preparo em minutos.', null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='rating',
            field=models.FloatField(blank=True, help_text='Avaliação (1-5).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='diet',
            name='target_calories',
            field=models.FloatField(blank=True, help_text='Meta diária de calorias.', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='diet',
            name='target_carbs',
            field=models.FloatField(blank=True, help_text='Meta diária de carboidratos (g).', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='diet',
            name='target_fat',
            field=models.FloatField(blank=True, help_text='Meta diária de gordura (g).', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='diet',
            name='target_protein',
            field=models.FloatField(blank=True, help_text='Meta diária de proteína (g).', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='diet',
            name='water_intake_ml',
            field=models.PositiveIntegerField(blank=True, help_text='Meta diária de água (ml).', null=True),
        ),
        migrations.AlterField(
            model_name='dietfeedback',
            name='feedback_text',
            field=models.TextField(blank=True, help_text='Comentário adicional.', null=True),
        ),
    ]
